import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import Header from "@/components/Header";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Intro from "@/components/Intro";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased` + " bg-slate-100"}
        >
          <ClerkLoading>
            
          </ClerkLoading>
          <ClerkLoaded>
            <Header />
              <Intro/>
            {children}
          </ClerkLoaded>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
