import Loader from '@/components/Loader';
import '.././globals.css';
import {ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/Header';



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className= "bg-slate-100">
          <ClerkLoading>
            <Loader/>
          </ClerkLoading>
          <ClerkLoaded>
            <Header/>
            {children}
         </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}